server:
  port: 8082

spring:
  application:
    name: policy-service

  datasource:
    url: jdbc:mysql://localhost:3306/policydb
    username: root
    password: linux123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
