#server:
#  port: 8082
#
#spring:
#  application:
#    name: policy-service
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/policydb
#    username: root
#    password: linux123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082

spring:
  application:
    name: policy-service

  datasource:
    # Use DB_HOST if provided; default to localhost when running on your laptop.
    url: jdbc:mysql://${DB_HOST:localhost}:3306/policydb
    username: root
    # Use DB_PASSWORD if provided; default to linux123 when running locally.
    password: ${DB_PASSWORD:linux123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      # Use EUREKA_HOST if provided; default to localhost when running locally.
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

