version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"                  # change host port if local MySQL conflicts
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d   # <-- contains init.sql
    networks:
      - insurance-network

  eurekaserver:
    build: ./eurekaServer
    container_name: eurekaserver
    ports:
      - "8761:8761"
    networks:
      - insurance-network

  apigateway:
    build: ./apiGateway
    container_name: apigateway
    ports:
      - "8090:8090"
    environment:
      EUREKA_HOST: eurekaserver
    depends_on:
      - eurekaserver
    networks:
      - insurance-network

  userservice:
    build: ./userService
    container_name: userservice
    environment:
      DB_HOST: mysql
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      EUREKA_HOST: eurekaserver
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - eurekaserver
    networks:
      - insurance-network

  claimservice:
    build: ./claimService
    container_name: claimservice
    environment:
      DB_HOST: mysql
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      EUREKA_HOST: eurekaserver
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - eurekaserver
    networks:
      - insurance-network

  policyservice:
    build: ./policyService
    container_name: policyservice
    environment:
      DB_HOST: mysql
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      EUREKA_HOST: eurekaserver
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - eurekaserver
    networks:
      - insurance-network

  notificationservice:
    build: ./notificationService
    container_name: notificationservice
    environment:
      DB_HOST: mysql
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      EUREKA_HOST: eurekaserver
    ports:
      - "8084:8084"
    depends_on:
      - mysql
      - eurekaserver
    networks:
      - insurance-network

networks:
  insurance-network:

volumes:
  mysql-data:
