#server:
#  port: 8090
#
#spring:
#  application:
#    name: api-gateway
#
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lowerCaseServiceId: true
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            # Match both /users and anything under it
#            - Path=/users/**
#        - id: policy-service
#          uri: lb://policy-service
#          predicates:
#            - Path=/policies/**
#        - id: claim-service
#          uri: lb://claim-service
#          predicates:
#            - Path=/claims/**
#        - id: notification-service
#          uri: lb://notification-service
#          predicates:
#            - Path=/notifications/**
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
#
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
          lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: policy-service
          uri: lb://policy-service
          predicates:
            - Path=/policies/**
        - id: claim-service
          uri: lb://claim-service
          predicates:
            - Path=/claims/**
        - id: notificationService
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**



logging:
  level:
    org.springframework.cloud.gateway: DEBUG


