server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: linux123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  jwt:
    secret: mySuperSecretKey12345   # 👈 Already fixed earlier
    expiration-ms: 3600000          # 👈 ADD THIS (1 hour in milliseconds)
