#server:
#  port: 8084
#
#spring:
#  application:
#    name: notification-service
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/notificationdb
#    username: root
#    password: linux123
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

server:
  port: 8084

spring:
  application:
    name: notification-service

  datasource:
    # Use DB_HOST if set (Docker), otherwise default to localhost
    url: jdbc:mysql://${DB_HOST:localhost}:3306/notificationdb
    username: root
    # Use DB_PASSWORD if set (Docker), otherwise default to linux123
    password: ${DB_PASSWORD:linux123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      # Use EUREKA_HOST if set (Docker), otherwise default to localhost
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

